CREATE TABLE "settings_mirror" (
  "id" SERIAL PRIMARY KEY,
  "broker" TEXT NOT NULL UNIQUE,
  "enabled" BOOLEAN NOT NULL DEFAULT false,
  "lotsMode" TEXT NOT NULL DEFAULT 'fixed',
  "lots" DOUBLE PRECISION NOT NULL DEFAULT 0.01,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
