ALTER TABLE "backtest_setups" ADD COLUMN "weakCandles" TIMESTAMP(3)[] NOT NULL DEFAULT ARRAY[]::TIMESTAMP[];
ALTER TABLE "backtest_setups" ADD COLUMN "strongCandles" TIMESTAMP(3)[] NOT NULL DEFAULT ARRAY[]::TIMESTAMP[];
